// Package turkish provides normalization utilities for Turkish character handling
// in legacy MSSQL databases.
//
// # Background
//
// Many Turkish ERP systems (e.g. Logo, Netsis, Mikro) store text data in
// varchar/char columns with Turkish_CI_AS (Windows-1254 / code page 1254) collation.
// These systems typically store names in uppercase ASCII:
//
//	"HÜSEYIN" → "HUSEYIN"
//	"İSTANBUL" → "ISTANBUL"
//
// When an AI assistant generates a query like:
//
//	SELECT * FROM MUSTERI WHERE ADI = 'Hüseyin'
//
// the database may return zero results because it performs a byte-level comparison
// and "Hüseyin" ≠ "HUSEYIN" even with CI (case-insensitive) collation when the
// character encoding differs.
//
// # What this package provides
//
//  1. NormalizeSQLLiterals – rewrites Turkish characters inside SQL single-quoted
//     string literals to their ASCII uppercase equivalents before the query is sent.
//
//  2. ToASCIIUpper – converts an arbitrary string to uppercase ASCII by replacing
//     every Turkish character with its closest ASCII counterpart.
//
//  3. FixMojibake – corrects the most common mojibake pattern that occurs when
//     Windows-1254 (Turkish) encoded bytes are mistakenly decoded as Windows-1252
//     (Western European / Latin-1 superset). This can happen with older ODBC/JDBC
//     bridges or misconfigured data pipelines.
//
//  4. FixResultValue – convenience wrapper for FixMojibake that accepts any
//     interface{} value (string or []byte) and returns the fixed value.
package turkish

import (
	"regexp"
	"strings"
)

// turkishToASCII maps every Turkish-specific character to its closest ASCII
// uppercase equivalent.  Both uppercase and lowercase Turkish variants are
// included so the replacer can be applied after or before strings.ToUpper.
//
// Mapping rationale:
//   - İ (U+0130 LATIN CAPITAL LETTER I WITH DOT ABOVE) → I
//   - ı (U+0131 LATIN SMALL LETTER DOTLESS I)          → I  (upper of ı is I in Turkish)
//   - Ş/ş → S,  Ğ/ğ → G,  Ü/ü → U,  Ö/ö → O,  Ç/ç → C
//   - Circumflex variants used in Ottoman loanwords: Â/â→A, Î/î→I, Û/û→U
var turkishToASCII = strings.NewReplacer(
	// Uppercase
	"İ", "I",
	"Ş", "S",
	"Ğ", "G",
	"Ü", "U",
	"Ö", "O",
	"Ç", "C",
	// Lowercase (become uppercase ASCII)
	"ı", "I",
	"ş", "S",
	"ğ", "G",
	"ü", "U",
	"ö", "O",
	"ç", "C",
	// Circumflex variants
	"Â", "A", "â", "A",
	"Î", "I", "î", "I",
	"Û", "U", "û", "U",
)

// singleQuoteRe matches SQL single-quoted string literals.
// It handles the SQL standard escape for a literal single-quote: two consecutive
// single-quotes (”).
//
// Pattern breakdown:
//
//	'         – opening quote
//	(?:       – non-capturing group
//	  [^']    – any character that is not a single-quote
//	  |''     – OR two consecutive single-quotes (escaped quote)
//	)*        – zero or more of the above
//	'         – closing quote
var singleQuoteRe = regexp.MustCompile(`'(?:[^']|'')*'`)

// NormalizeSQLLiterals rewrites single-quoted SQL string literals so that
// Turkish characters inside them are converted to their ASCII uppercase
// equivalents.
//
// This is the primary entry-point for the query normalization middleware.
// It transforms queries generated by an AI assistant into a form that is
// compatible with old Turkish ERP databases that store data as uppercase ASCII.
//
// Only the contents of string literals are modified — SQL keywords, column
// names, and the rest of the query syntax are left completely untouched.
//
// Examples:
//
//	Input:  SELECT * FROM MUSTERI WHERE ADI = 'Hüseyin'
//	Output: SELECT * FROM MUSTERI WHERE ADI = 'HUSEYIN'
//
//	Input:  SELECT * FROM URUN WHERE ACIKLAMA LIKE '%şeker%'
//	Output: SELECT * FROM URUN WHERE ACIKLAMA LIKE '%SEKER%'
//
//	Input:  SELECT * FROM SEHIR WHERE AD = 'İstanbul' OR AD = 'Çanakkale'
//	Output: SELECT * FROM SEHIR WHERE AD = 'ISTANBUL' OR AD = 'CANAKKALE'
func NormalizeSQLLiterals(query string) string {
	return singleQuoteRe.ReplaceAllStringFunc(query, func(literal string) string {
		// Strip surrounding single-quotes, normalize content, re-wrap.
		inner := literal[1 : len(literal)-1]
		inner = strings.ToUpper(inner)        // uppercase standard Latin chars
		inner = turkishToASCII.Replace(inner) // replace remaining Turkish uppercase chars
		return "'" + inner + "'"
	})
}

// ToASCIIUpper converts s to uppercase and replaces all Turkish-specific
// characters with their ASCII equivalents.
//
// Useful for generating normalized display values or search keys outside of
// a full SQL query context.
//
// Examples:
//
//	ToASCIIUpper("Hüseyin")  → "HUSEYIN"
//	ToASCIIUpper("İstanbul") → "ISTANBUL"
//	ToASCIIUpper("çiçek")    → "CICEK"
func ToASCIIUpper(s string) string {
	return turkishToASCII.Replace(strings.ToUpper(s))
}

// mojibakeReplacer corrects the most common mojibake pattern for Turkish text:
// Windows-1254 (Turkish) encoded bytes mistakenly decoded as Windows-1252
// (Western European).
//
// The two code pages share most byte values but differ at several positions
// that happen to be the unique Turkish characters:
//
//	Byte  Windows-1252  Windows-1254  (what we receive → what it should be)
//	0xD0  Ð             Ğ             "Ð" → "Ğ"
//	0xDD  Ý             İ             "Ý" → "İ"
//	0xDE  Þ             Ş             "Þ" → "Ş"
//	0xF0  ð             ğ             "ð" → "ğ"
//	0xFD  ý             ı             "ý" → "ı"
//	0xFE  þ             ş             "þ" → "ş"
var mojibakeReplacer = strings.NewReplacer(
	"Ð", "Ğ",
	"Ý", "İ",
	"Þ", "Ş",
	"ð", "ğ",
	"ý", "ı",
	"þ", "ş",
)

// FixMojibake corrects strings where Windows-1254 (Turkish) encoded bytes were
// mistakenly decoded as Windows-1252 (Western European / Latin-1 superset).
//
// Apply this to query result strings when you see Latin characters like
// Ð, Ý, Þ, ð, ý, þ in positions where Turkish characters (Ğ, İ, Ş, ğ, ı, ş)
// are expected.
//
// This is a targeted, heuristic fix. It does not use full re-encoding because
// Go strings are already UTF-8 by the time the result is returned from the
// database driver; we can only correct the characters we know are wrong.
//
// If you need full re-encoding, use the golang.org/x/text/encoding/charmap
// package directly.
//
// Examples:
//
//	FixMojibake("ÝSTANbul") → "İSTANbul"
//	FixMojibake("HüSEYÝN")  → "HüSEYİN"   (non-Turkish chars are untouched)
//	FixMojibake("SAÐLIK")   → "SAĞLIK"
func FixMojibake(s string) string {
	return mojibakeReplacer.Replace(s)
}

// FixResultValue applies FixMojibake to string-typed database result values.
// Other value types (int, float64, time.Time, nil, etc.) are returned unchanged.
//
// This function is intended to be called inside the result-row scanning loop
// of the MSSQL adapter when normalize_turkish is enabled.
func FixResultValue(v any) any {
	switch s := v.(type) {
	case string:
		fixed := FixMojibake(s)
		if fixed == s {
			return v // avoid allocation when nothing changed
		}
		return fixed
	case []byte:
		fixed := FixMojibake(string(s))
		return fixed
	default:
		return v
	}
}
